plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.6'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.examplle'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'

	// Spring Boot Data Redis (버전은 보통 상위 프로젝트 설정에 따라 자동 결정됩니다)
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	
	implementation 'org.springframework.boot:spring-boot-starter-json'

	// Pool 연결 설정을 위한 commons-pool2
	implementation 'org.apache.commons:commons-pool2:2.11.1'

	// Redis Enterprise에서 권장하는 Jedis 클라이언트[cite: 1]
	implementation 'redis.clients:jedis:5.2.0'

	implementation 'com.fasterxml.jackson.core:jackson-databind'
	implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8'
	implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

	implementation 'org.springframework.boot:spring-boot-starter-web'

	// JDBC 사용 시
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'
	// 또는 JPA 사용 시
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	// H2 같은 인메모리 DB라도 있어야 TransactionManager가 활성화됩니다.
	runtimeOnly 'com.h2database:h2'

}

tasks.named('test') {
	useJUnitPlatform()
}
